### ISSUE TITLE
Feature request - measuring radius/diameter

### ISSUE THREAD

**Issue by guirnab** [MeshInspector/MeshInspector#136]
Hello,

I really miss an easy way to measure radius/diameter. Something similar to NetFabb:
![Recording 2024-02-07 105610](https://github.com/MeshInspector/MeshInspector/assets/7635266/6f8e2b7f-81cd-4f63-a094-cc7e5f095cb2)

**Comment by egorbovskoy** [comment]
> Hello,
> 
> I really miss an easy way to measure radius/diameter. Something similar to NetFabb: ![Recording 2024-02-07 105610](https://private-user-images.githubusercontent.com/7635266/302938684-6f8e2b7f-81cd-4f63-a094-cc7e5f095cb2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTg2MjksIm5iZiI6MTcwNzg5ODMyOSwicGF0aCI6Ii83NjM1MjY2LzMwMjkzODY4NC02ZjhlMmI3Zi04MWNkLTRmNjMtYTA5NC1jYzdlNWYwOTVjYjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMDgxMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI0MTVmNTA5OTgxMzc2NjAzNzMxMzc1ODM1M2EzOTljODAzMGRkM2RjNTEwY2M5MzA4ZjI0Yzc1YTIyMzE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l1GkMUXLpjbcVInrDIJa7kMqKlb47yHU22WjjBgQHPo) [ ![Recording 2024-02-07 105610](https://private-user-images.githubusercontent.com/7635266/302938684-6f8e2b7f-81cd-4f63-a094-cc7e5f095cb2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTg2MjksIm5iZiI6MTcwNzg5ODMyOSwicGF0aCI6Ii83NjM1MjY2LzMwMjkzODY4NC02ZjhlMmI3Zi04MWNkLTRmNjMtYTA5NC1jYzdlNWYwOTVjYjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMDgxMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI0MTVmNTA5OTgxMzc2NjAzNzMxMzc1ODM1M2EzOTljODAzMGRkM2RjNTEwY2M5MzA4ZjI0Yzc1YTIyMzE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l1GkMUXLpjbcVInrDIJa7kMqKlb47yHU22WjjBgQHPo) ](https://private-user-images.githubusercontent.com/7635266/302938684-6f8e2b7f-81cd-4f63-a094-cc7e5f095cb2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTg2MjksIm5iZiI6MTcwNzg5ODMyOSwicGF0aCI6Ii83NjM1MjY2LzMwMjkzODY4NC02ZjhlMmI3Zi04MWNkLTRmNjMtYTA5NC1jYzdlNWYwOTVjYjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMDgxMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI0MTVmNTA5OTgxMzc2NjAzNzMxMzc1ODM1M2EzOTljODAzMGRkM2RjNTEwY2M5MzA4ZjI0Yzc1YTIyMzE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l1GkMUXLpjbcVInrDIJa7kMqKlb47yHU22WjjBgQHPo) [ ](https://private-user-images.githubusercontent.com/7635266/302938684-6f8e2b7f-81cd-4f63-a094-cc7e5f095cb2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTg2MjksIm5iZiI6MTcwNzg5ODMyOSwicGF0aCI6Ii83NjM1MjY2LzMwMjkzODY4NC02ZjhlMmI3Zi04MWNkLTRmNjMtYTA5NC1jYzdlNWYwOTVjYjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMDgxMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI0MTVmNTA5OTgxMzc2NjAzNzMxMzc1ODM1M2EzOTljODAzMGRkM2RjNTEwY2M5MzA4ZjI0Yzc1YTIyMzE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l1GkMUXLpjbcVInrDIJa7kMqKlb47yHU22WjjBgQHPo)

Hello Jiří. 
We released a release with experimental feature support. 
To try it out, you can enable experimental features in the settings.

https://github.com/MeshInspector/MeshInspector/assets/68220796/0fc86dea-abad-49de-89c2-12adeddb16f9


Again, this functionality is under active development and testing. Therefore, various bugs may occur. We would also appreciate your ideas and comments.

**Comment by Fedr** [comment]
Hello @guirnab ,

Have you tried Features and Measurements in MeshInspector as presented above? It is recommended to use the latest release from https://meshinspector.com/download/ and active the experimental features in Settings.

**Comment by guirnab** [comment]
Hi @Fedr,

yes, with the refine button it works well. Thanks!
