### ISSUE TITLE
feature require: more file format support

### ISSUE THREAD

**Issue by feifeizuo** [MeshInspector/MeshInspector#137]
It would be valuable for users if the software supported GLB and DRC formats.  Thanks

**Comment by Fedr** [comment]
Actually we already support GLB format:
![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/4c20618f-3de2-4fca-86aa-31672741c4d0)
Please let us know if it does not work for some case.

As to DRC, yes it is a good idea to support it as well. We will add it in our plans.

**Comment by feifeizuo** [comment]
when i load glb mesh, this is error . <img width="284" alt="image" src="https://github.com/MeshInspector/MeshInspector/assets/6001243/494dd15f-869b-48c6-828d-6c52b7d8f9a9">

**Comment by Fedr** [comment]
Could you please attach your .glb mesh for us to reproduce this?

**Comment by feifeizuo** [comment]
yes, i upload it .
[Uploading model.zip…]()

**Comment by feifeizuo** [comment]
yes , i have upload it . [model.zip](https://github.com/MeshInspector/MeshInspector/files/15303727/model.zip)

**Comment by Fedr** [comment]
Thanks for the data. In the next release (hopefully next week), such models will be opened successfully:

![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/f9dbc699-1369-4978-b619-5cba53771d76)

**Comment by feifeizuo** [comment]
Thanks very much
