### ISSUE TITLE
Invisible selection with "Select Primitives" Tool

### ISSUE THREAD

**Issue by emil-peters** [MeshInspector/MeshInspector#139]
When selecting with the Lasso in Select primitives you get a visual of what you're about to select.
When "minimizing" the window, but not closing it, you can still select using the lasso tool, but the visualization is not present.

See video for more information

[Screencast from 26-08-24 08:05:15.webm](https://github.com/user-attachments/assets/55716795-6e7a-490b-ade9-57a488a33fbe)

Not sure if this is the intended behavior, but it feels a bit unintuitive.

Kind regards,
Emil

**Comment by Grantim** [comment]
Hello!
Thanks for reporting, it looks like a but, we will fix it until next release!

**Comment by Grantim** [comment]
Hello,
We have just released new version of MeshInspector, with fix of this issue!

**Comment by Grantim** [comment]
Closing, please reopen if needed
