### ISSUE TITLE
Weird continued behaviour of "Select Primitives" tool

### ISSUE THREAD

**Issue by emil-peters** [MeshInspector/MeshInspector#140]
When creating a selecting with the lasso tool, pressing `esc` and then opening the Select Primitives tool again, the lasso tool shape continues from where it ended before.
It also keep following the mouse while not opened.

See video below for more info

[Screencast from 26-08-24 08:10:12.webm](https://github.com/user-attachments/assets/1c16d974-00f3-4570-b179-a8812fbc58be)

**Comment by Grantim** [comment]
Hello!
Thanks for reporting, it looks like a but, we will fix it until next release!

**Comment by Grantim** [comment]
Hello,
We have just released new version of MeshInspector, with fix of this issue!

**Comment by Grantim** [comment]
Closing, please reopen if needed
