### ISSUE TITLE
Flashback after running the startup interface.

### ISSUE THREAD

**Issue by BlackantHermit** [MeshInspector/MeshInspector#83]
I have been using MeshInspector for a while after downloading it, but now when I start the software the startup screen appears and then it flashes. This has already happened on two PCs with Win11.

**Comment by BlackantHermit** [comment]
> 
I pasted Log and hope it will help you to improve it. I tried your method to delete the config.json and the software starts successfully!

**Comment by Grantim** [comment]
Thank you!

**Comment by Fedr** [comment]
The problem most probably will reoccur and you will need to delete `config.json` once again. We will create new build with the fix soon.

**Comment by Fedr** [comment]
Please use release [v0.0.125.24](https://github.com/MeshInspector/MeshInspector/releases/tag/v0.0.125.24). If the startup issue happens again, please send us `config.json` from your computer.

**Comment by BlackantHermit** [comment]
> Please use release [v0.0.125.24](https://github.com/MeshInspector/MeshInspector/releases/tag/v0.0.125.24). If the startup issue happens again, please send us `config.json` from your computer.

Okay, I'll use it for a few days first.

**Comment by BlackantHermit** [comment]
I don't have any more flashbacks.
