### ISSUE TITLE
Error opening some obj files

### ISSUE THREAD

**Issue by BlackantHermit** [MeshInspector/MeshInspector#84]
I downloaded some obj model files from https://casual-effects.com/data/ opening it with MeshInspector gives an error.
For example, if you open bunny.obj, it will appear: `OBJ-format read error`
The same situation seems to occur with other models on this website. I use other software, such as meshlab, to open the model successfully.

**Comment by Fedr** [comment]
MeshLib can already open these files (without texture):
![image](https://user-images.githubusercontent.com/3136125/203605947-2d37b58b-9148-409e-bf6f-bf8fdf61dc11.png)
We will make MeshInspector release before end of week.

**Comment by BlackantHermit** [comment]
> MeshLib can already open these files (without texture):
> 
> ![image](https://user-images.githubusercontent.com/3136125/203605947-2d37b58b-9148-409e-bf6f-bf8fdf61dc11.png)
> 
> We will make MeshInspector release before end of week.

That's great. Look forward to your project😁

**Comment by Fedr** [comment]
Fixed in release [v0.0.125.24](https://github.com/MeshInspector/MeshInspector/releases/tag/v0.0.125.24). Please verify.

**Comment by BlackantHermit** [comment]
> Fixed in release [v0.0.125.24](https://github.com/MeshInspector/MeshInspector/releases/tag/v0.0.125.24). Please verify.

I downloaded the latest version and tested it, the obj model that would have been opened with an error can now be opened successfully!
