### ISSUE TITLE
Maybe you can support more language characters

### ISSUE THREAD

**Issue by BlackantHermit** [MeshInspector/MeshInspector#85]
When I open a model with Chinese characters in its name, its name is not displayed properly in the software, can you support more characters in different languages?

**Comment by Grantim** [comment]
Hi!
We are working on it now. How do you think will [Simplified Chinese characters](https://en.wikipedia.org/wiki/Simplified_Chinese_characters) be enough?

**Comment by BlackantHermit** [comment]
> 

Yes. Simplified Chinese characters can meet my needs.

**Comment by BlackantHermit** [comment]
> Hi! We are working on it now. How do you think will [Simplified Chinese characters](https://en.wikipedia.org/wiki/Simplified_Chinese_characters) be enough?

Yes. Simplified Chinese characters can meet my needs.

**Comment by BlackantHermit** [comment]
> Hi! In new release we added support for simplified Chinese glyphs https://github.com/MeshInspector/MeshInspector/releases/tag/v0.0.127.45

I used it, that's good☺

**Comment by Grantim** [comment]
Ok, thanks! Closing issue for now, you can reopen it if needed or rise a new one
